name: Update IPTV List

on:
  schedule:
    - cron: "0 3 * * *"   # 每天凌晨3点 UTC (北京时间 11:00) 自动运行
  workflow_dispatch:       # 手动触发按钮

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          pip install requests

      - name: Run IPTV script
        run: |
          python3 iptv_merge.py

      - name: Commit and push results
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add merged.m3u output_m3u/
          git commit -m "Auto update IPTV list [$(date '+%Y-%m-%d %H:%M:%S')]"
          git push
